name: Build and Deploy to Render

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main   

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  

      - name: Install dependencies
        run: npm install
        working-directory: client/vite-project  

      - name: Build the app
        run: npm run build
        working-directory: client/vite-project  

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: client/vite-project/dist  

  deploy:
    runs-on: ubuntu-latest
    needs: build
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: dist
  
      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -X POST \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "Accept: application/json" \
          -H "Content-Type: application/json" \
          -d '{"clear_cache":false}' \
          "https://api.render.com/v1/services/srv-cqrj9olumphs73clcsvg/deploys"
